### ISSUE TITLE
Links broken on stdlib index (but not table of contents)

### ISSUE THREAD

**Issue by hosted-fornet** [urbit/developers.urbit.org#32]
https://developers.urbit.org/reference/hoon/stdlib links appear to be broken (compare to https://developers.urbit.org/reference/hoon/stdlib/table-of-contents)

See attached:
![Screenshot from 2022-06-30 16-00-59](https://user-images.githubusercontent.com/79381743/176792679-aabea9ef-81a0-43f2-b12b-af07f4eb25cf.png)
![Screenshot from 2022-06-30 16-01-07](https://user-images.githubusercontent.com/79381743/176792685-68c6f18d-103e-4b7d-99c1-86d7caa801a5.png)

**Comment by hosted-fornet** [comment]
Update: a few of the links further down the page on the `/table-of-contents` page are broken as well.

**Comment by matildepark** [comment]
Oh right. Because I fixed it before then. We should just merge the toc page into the index.md now.

**Comment by sigilante** [comment]
@hosted-fornet does the behavior seem to be resolved for you now?

**Comment by hosted-fornet** [comment]
Much better, but I still see a few stragglers just scanning through the page, e.g.:

![230118-stdlib-0](https://user-images.githubusercontent.com/79381743/213258510-9058dd29-44f5-4a0b-96d0-188053f54ae6.png)
![230118-stdlib-1](https://user-images.githubusercontent.com/79381743/213258513-73c81031-8acc-4aca-b9e7-9535980d85e7.png)
![230118-stdlib-2](https://user-images.githubusercontent.com/79381743/213258515-3a37d13d-6d1b-47c7-aba1-4e4cb8f994b8.png)
